// src/frontend/ecommerce-react/src/components/skeleton/index.tsx
import { ReactElement } from "react";

export const Skeleton = (): ReactElement => {
  return (
    <div className="w-96 h-80 border-2 rounded-md mx-auto mt-20">
      <div className="flex animate-pulse flex-row items-center h-full justify-center space-x-5">
        <div className="flex flex-col space-y-3">
          <div className="w-80 bg-gray-300 h-40 rounded-md">
          </div>
          <div className="w-80 bg-gray-300 h-6 rounded-md">
          </div>
          <div className="w-60 bg-gray-300 h-6 rounded-md">
          </div>
          <div className="w-40 bg-gray-300 h-6 rounded-md">
          </div>
        </div>
      </div>
    </div>
  );
}

// src/frontend/ecommerce-vue/src/components/skeleton/index.vue
<template>
  <div class="w-96 h-80 border-2 rounded-md mx-auto mt-4">
    <div class="flex animate-pulse flex-row items-center h-full justify-center space-x-5">
      <div class="flex flex-col space-y-3">
        <div class="w-80 bg-gray-300 h-40 rounded-md">
        </div>
        <div class="w-80 bg-gray-300 h-6 rounded-md">
        </div>
        <div class="w-60 bg-gray-300 h-6 rounded-md">
        </div>
        <div class="w-40 bg-gray-300 h-6 rounded-md">
        </div>
      </div>
    </div>
  </div>
</template>

<script src="./_index.ts" lang="ts"></script>
