// src/frontend/ecommerce-vue/src/app/products/infrastructure/ui/containers/product-detail/index.vue
<template>
    <div class="flex flex-wrap m-4">
        <template v-if="showSkeleton">
          <skeleton />
        </template>
      <template v-if="product?.id">
        <div className="xl:w-1/3 md:w-1/2 p-4">
          <product :price="product.price" :picture="product.picture" :name="product.name" />
        </div>
      </template>
    </div>
</template>

<script src="./_index.ts" lang="ts"></script>

// src/frontend/ecommerce-react/src/app/products/infrastructure/ui/containers/product-detail/index.tsx
// Dependencies
import { ReactElement } from "react";
import { useParams } from "react-router-dom";

// Componentes
import { Product } from "@ecommerce/app/products/infrastructure/ui/components/product";
import { Skeleton } from "@ecommerce/components/skeleton";

// Commons
import { STATUS_TYPES } from '@ecommerce/commons/app';

// Hooks
import { useGetProductDetail } from "./hooks";

export const ProductDetail = (): ReactElement => {
  const { id } = useParams<any>();
  const [status, product] = useGetProductDetail(id);
  return (
    <div className="flex flex-wrap m-4">
      {
        status === STATUS_TYPES.LOADING && (
          <Skeleton />
        )
      }
      {
        product?.id && (
          <div className="xl:w-1/3 md:w-1/2 p-4">
            <Product picture={product.picture} name={product.name} price={product.price} />
          </div>
        )
      }
    </div>
  )
}
